### ISSUE TITLE
在打开部分作品详情后浏览时闪退

### ISSUE THREAD

**Issue by StarHeartHunt** [CeuiLiSA/Pixiv-Shaft#262]
**描述问题：**

[举例](https://www.pixiv.net/artworks/87869906) 
在使用 Shaft 打开该作品并向下滑动时，在某一p必定闪退

**如何复现？**

1. 使用 Shaft 打开[举例](https://www.pixiv.net/artworks/87869906) 
2. 向下滑动
3. 在某一p闪退

**环境信息：**

 - OS:Android 10, MIUI 12 20.9.4开发版
 - Device: 小米 MIX 3
 - Shaft: 3.0.6

**日志**

```java
java.lang.RuntimeException: Canvas: trying to draw too large(107539200bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:233)
	at android.widget.ImageView.onDraw(ImageView.java:1434)
	at android.view.View.draw(View.java:21514)
	at android.view.View.updateDisplayListIfDirty(View.java:20389)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.View.draw(View.java:21244)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21517)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
	at android.view.View.updateDisplayListIfDirty(View.java:20389)
	at android.view.View.draw(View.java:21244)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:811)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21517)
	at android.view.View.updateDisplayListIfDirty(View.java:20389)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20349)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3530)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2867)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1818)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:865)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
```

**Comment by sunbeams001** [comment]
是最新版应用吗，这个问题在 #237 修过

**Comment by StarHeartHunt** [comment]
> 是最新版应用吗，这个问题在 #237 修过

使用版本`3.0.5`

**Comment by SodaWithoutSparkles** [comment]
刚刚试过了，现在还是。大概到举例的第12张图左右吧。除此之外没见过。

**Comment by sunbeams001** [comment]
应该是第27P吧，这张图不很高，但是长宽都很到了6000多导致总体过大了
