### ISSUE TITLE
分享以图搜源结果会崩掉

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#274]
看见图片→分享到shaft并以图搜源→找到源头→右上角分享→应用已崩溃

**Comment by sunbeams001** [comment]
有一些报错提示或日志吗，啥手机这能崩也不容易

**Comment by CeuiLiSA** [comment]
加我qq  863043461   给你发个带bugly的shaft，方便我们看问题原因

**Comment by SodaWithoutSparkles** [comment]
刚刚试了一下，看到MIUI的报错日志
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=data:text/html; charset=UTF-8;charset=utf-8;base64, }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2066)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:568)
	at android.app.Activity.startActivityForResult(Activity.java:5216)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:554)
	at android.app.Activity.startActivity(Activity.java:5587)
	at android.app.Activity.startActivity(Activity.java:5555)
	at ceui.lisa.fragments.FragmentWebView.lambda$initView$1$FragmentWebView(FragmentWebView.java:131)
	at ceui.lisa.fragments.-$$Lambda$FragmentWebView$WZc8ufGKtSoeLYJFDecPJRUAOxs.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7185)
	at android.view.View.performClickInternal(View.java:7162)
	at android.view.View.access$3500(View.java:819)
	at android.view.View$PerformClick.run(View.java:27684)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by sunbeams001** [comment]
呃，saucenao里面右上角那里不是分享，是在浏览器打开，你可以点进插画详情点右上角分享

**Comment by soloopooo** [comment]
我刚刚用我的小米9试了试，一样的错误与日志，考虑更换一下浏览器调用方式？

**Comment by CeuiLiSA** [comment]
现在改了，只有通过一个明确的url跳转到这个页面的时候，会显示右上角的按钮，其他时候隐藏了

**Comment by SodaWithoutSparkles** [comment]
> 呃，saucenao里面右上角那里不是分享，是在浏览器打开，你可以点进插画详情点右上角分享

在浏览器打开之后可以选择浏览器，你想的话会有一种插件叫"复制链接到剪贴板"，之后就可以分享了。

不过这个按钮正确用法应该是在浏览器打开吧

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 插画页右上角菜单-复制作品链接

**Comment by SodaWithoutSparkles** [comment]
> @SodaWithoutSparkles 插画页右上角菜单-复制作品链接

原来还有这个功能，谢谢
