### ISSUE TITLE
小米k20和k60进去会闪退，有人说的卸载更新webview但只能清除数据，华为进去正常

### ISSUE THREAD

**Issue by purvoid** [CeuiLiSA/Pixiv-Shaft#551]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.4，2.1也试过

### Android system version

miui14

### Device model

redmi k60

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

安装后点击进入白屏一会就会闪退

### Expected behavior / 期望行为

要是正常进去就好

### Actual behavior / 实际行为

进不去

**Comment by purvoid** [comment]
问题trace：
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:121)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)
	at ceui.lisa.activities.Shaft.onCreate(Shaft.java:84)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1278)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7081)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
