### ISSUE TITLE
正常浏览图片(后台在下载图片中发生闪退)

### ISSUE THREAD

**Issue by naloder** [CeuiLiSA/Pixiv-Shaft#74]
机型:小米8lite
系统:MIUI 11 2.3.9 安卓10

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at ceui.lisa.fragments.FragmentSingleIllust.initData(FragmentSingleIllust.java:126)
	at ceui.lisa.fragments.BaseBindFragment.onCreateView(BaseBindFragment.java:73)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7923)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3331)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by CeuiLiSA** [comment]
抱歉这种小范围且不好复现的问题我处理不了。。处理的优先级稍微放低一点了

**Comment by duzhaokun123** [comment]
问一下在浏览图片时是否进行了转屏等改变应用窗口尺寸的操作

另外这个日志可能不是第一次崩溃时记录
